[project]
name = "vimes"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Laya Binu", email = "layambinu@gmail.com" }
]
requires-python = ">=3.10, <3.15"
classifiers = [
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    "astro-tulips>=1.0.3",
    "h5py>=3.16.0",
    "imageio>=2.37.3",
    # 2.3.2 is the earliest version with Python 3.14 support
    # https://numpy.org/doc/stable/release/2.3.2-notes.html
    "numpy>=2.3.2",
    "pillow>=12.2.0",
    "pygame>=2.6.1",
]

[project.scripts]
vimes-preprocess = "vimes.cli:preprocess"
vimes = "vimes.cli:animate"

[tool.ruff.lint]
# Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`) codes by default.
# Unlike Flake8, Ruff doesn't enable pycodestyle warnings (`W`) or
# McCabe complexity (`C901`) by default.
select = [
    # pycodestyle
    "E",
    # pycodestyle-warnings
    "W",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
]

[build-system]
requires = ["uv_build>=0.11.6,<0.12.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pyinstrument==5.1.2",
    "pytest==9.0.3",
    "ruff==0.15.14",
]
